### PR TITLE
Feedback if the master password is well entered

### PR DESCRIPTION
**Pull request by pmiossec**
To improve security:
- displayed only once a password is generated
- add an option to hide the icons (and generated password)

Preview:

- when sensitive data hidden: 
image

- when sensitive data are displayed:
image

### CODE REVIEW

**Comment by pmiossec** [comment]
(based on the previous PR)

What do you think about it?

**Comment by paulgreg** [comment]
I wouldn’t want to have that by default but the checkbox « hide sensitive data » is very nice !
So I think it’s pretty good.
I’ve some remarks about the implementation hovewer. I’ll comment the line directly.
Do you plan to add it to the addon too ?

**Comment by paulgreg** [comment]
Thanks for the work. It’s nice.
A question : instead of committing directly font-awesome woff file into repo, do you think it’s doable to install it via npm (https://www.npmjs.com/package/font-awesome) and copy it via gulp.
So we don’t have those dependency in the repo ?

**Comment by pmiossec** [comment]
done

**Comment by pmiossec** [comment]
Thanks! :fireworks:

**Pull request merged**
